plugins {
  id 'com.android.application' version '8.12.2' apply false
  id 'com.android.library' version '8.12.2' apply false
}

ext {
  compileSdkVersion = 36
  minSdkVersion = 28
  targetSdkVersion = 36
  ndkVersion = '28.1.13356709'
  buildToolsVersion = '36.0.0'
  buildGradleVersion = '8.2.2'
//  ndkAbiFilters = ['x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a']

  mavenRepo = System.env.MVN_REPO ?: ""

}

