plugins {
  id 'com.android.library'
}

android {
    namespace 'com.squareup.duktape'
    compileSdk rootProject.ext.compileSdkVersion
    ndkVersion rootProject.ext.ndkVersion

  defaultConfig {
    minSdk 28
    targetSdk 36
//     ndk {
//       abiFilters(*rootProject.ext.ndkAbiFilters)
//     }
    externalNativeBuild {
      cmake {
        arguments '-DANDROID_TOOLCHAIN=clang', '-DANDROID_STL=c++_static'
        cFlags '-std=c99', '-fstrict-aliasing'
        cppFlags '-std=c++11', '-fstrict-aliasing', '-fexceptions'
      }
    }
  }
  buildTypes {
    release {
      externalNativeBuild {
        cmake {
          arguments '-DCMAKE_BUILD_TYPE=MinSizeRel'
          cFlags '-g0', '-Os', '-fomit-frame-pointer', '-DNDEBUG', '-fvisibility=hidden'
          cppFlags '-g0', '-Os', '-fomit-frame-pointer', '-DNDEBUG', '-fvisibility=hidden'
        }
      }
    }
    debug {
      externalNativeBuild {
        cmake {
          cFlags '-g', '-DDEBUG'
          cppFlags '-g', '-DDEBUG'
        }
      }
    }
  }
  externalNativeBuild {
    cmake {
      path "src/main/jni/CMakeLists.txt"
    }
  }
}

dependencies {
  implementation 'androidx.annotation:annotation:1.7.1'
}

task sourcesJar(type: Jar) {
  from android.sourceSets.main.java.srcDirs
  archiveClassifier = 'sources'
}

task javadoc(type: Javadoc) {
  source = fileTree(dir: "src/main/java", include: "**/*.java")
  classpath += files(android.bootClasspath)
  doFirst {
    def releaseCp = configurations.findByName("releaseCompileClasspath")
    if (releaseCp != null) classpath += files(releaseCp)
    def debugCp = configurations.findByName("debugCompileClasspath")
    if (debugCp != null) classpath += files(debugCp)
  }
}

task javadocJar(type: Jar, dependsOn: javadoc) {
  archiveClassifier = 'javadoc'
  from javadoc.destinationDir
}

artifacts {
  archives javadocJar
  archives sourcesJar
}
